### PR TITLE
fix: PromiseIndex type

### PR DESCRIPTION
**Pull request by matiasbenary**
## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/near/near-sdk-js/blob/master/CONTRIBUTING.md).
- [x] Commit messages follow the [conventional commits](https://www.conventionalcommits.org/) spec
- [x] **If this is a code change**: I have written unit tests.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

Currently there is an error in the type `PromiseIndex`. Currently it is defined as `(number | bigint) & PromiseIndexBrand`. Since `&` is the **intersection** operator, and that `PromiseIndexBrand == -1`, then the only valid value is `-1`.

This is an error since `PromiseIndex` is used to access a Promise Result, which is at lease `0` (if it exists).

We caught this with @gagdiez while testing the `cross contract calls` example. Notice that the error was not captured before because it only arises in Typescript (and not in JS, which the current `XCC` example is written in).

## Test Plan

Added a new version of the `cross contract call` written in TS

## Related issues/PRs

#379

### CODE REVIEW

**Comment by gagdiez** [comment]
Notice that the `CI` in `develop` is failing, this will be fixed by #377

**Comment by gagdiez** [comment]
@fospring @ailisp 

I would actually recommend to:
- rollback the last commit from `develop` (since it broke CI)
- merge this fix (which is more urgent, since ts-contract **cannot** make cross-contract calls)
- release near-sdk-js v1.0.1 (fix)
- continue with https://github.com/near/near-sdk-js/pull/377

**Review by gagdiez — APPROVED** [review]

**Comment by gagdiez** [comment]
@fospring this looks good to me

**Comment by fospring** [comment]
LGTM. thank you @matiasbenary @gagdiez

**Pull request merged**
