### PR TITLE
Workspaces 3.1.0

### PR DESCRIPTION
**Pull request by volovyk-s**
- worskpaces 3.1.0 with sandbox 0.0.12
- `createAndDeploy` replaced with `devDeploy`
- `macos` tests turned off because of sandbox issue (@ChaoticTempest , who is responsible for fixing it? Can we at least tag them, this issue affecting us a lot).
- tests refactored

### CODE REVIEW

**Comment by volovyk-s** [comment]
@BenKurrek can I ask you to test this branch in M1. Just clone it and run the tests.

**Review by ailisp — APPROVED** [review]
Looks great! Am i right that the sandbox on a local Mac is working, but just doesn't work on github ci?

**Comment by volovyk-s** [comment]
> Looks great! Am i right that the sandbox on a local Mac is working, but just doesn't work on github ci?

Yes!

**Comment by ChaoticTempest** [comment]
the issue is here https://github.com/near/nearcore/issues/7235, but so far no one is working on it

**Pull request merged**
