### PR TITLE
Update template, add test

### PR DESCRIPTION
**Pull request by ailisp**

### CODE REVIEW

**Comment by ailisp** [comment]
@volovyk-s CI seems to have some disk space issue. https://github.com/near/near-sdk-js/pull/60/commits/dc64fa2c30b86e76c5806194ac21d7f705550f86 was closest to success and I also want to use a npm version instead of `file:...` in this template, so user can copy paste. Could you release a new version with new qjsc binary?

**Review by volovyk-s — APPROVED** [review]
Nice! We can use it as a template project in a separate repo.

**Comment by ailisp** [comment]
Sounds good! Let me move it to a separate repo and close this

**Comment by volovyk-s** [comment]
We agreed to merge this after fixing CI.

**Pull request merged**
