### PR TITLE
TSC error suppression for latest versions

### PR DESCRIPTION
**Pull request by vunderkind**
## Problem summary
Newer versions of TypeScript seem to be throwing compile-time errors deep within the `lib.dom.ts` file, with the error looking something like this:

`"node_modules/typescript/lib/lib.dom.d.ts(14578,11): error TS2430: Interface 'WebGL2RenderingContext' incorrectly extends interface 'WebGL2RenderingContextBase'.\n"`

A quick and dirty fix is to skip library checks, [according to this discussion](https://github.com/moment/moment/issues/4459). That's what is contained in this pull request. 

## Env parameters
My machine, which recorded this issue, is a Macbook Pro (2019), running Node `v16.9.0`, npm `8.19.2` and TypeScript `v4.8.4`. This happened with the latest near app build via `npx create-near-app@latest`.

### CODE REVIEW

**Comment by ailisp** [comment]
Thank you @vunderkind . Please do a `yarn build` to pass the CI. Other than that, it looks good to me!

**Comment by vunderkind** [comment]
> Thank you @vunderkind . Please do a `yarn build` to pass the CI. Other than that, it looks good to me!

Thanks for your response. Doing so now!

**Comment by volovyks** [comment]
@vunderkind linter and build tests are not happy with these changes.
Can you run:
- yarn lint
- yarn format
- yarn build

and push?

**Comment by vunderkind** [comment]
@volovyks — thanks for the nudge! Ach, turned out I was modifying the file _in_ the `lib` folder instead of the `src`. Took your recommendation and it built fine on my end. Please re-trigger your pipeline and let me know if it passes now 😬

**Comment by vunderkind** [comment]
@volovyks — thanks for the nudge! Ach, turned out I was modifying the file _in_ the `lib` folder instead of the `src`. Took your recommendation and it built fine on my end. Please re-trigger your pipeline and let me know if it passes now 😬

**Review by ailisp — APPROVED** [review]
Looks good to me! Thanks @vunderkind !

**Pull request merged**
