### PR TITLE
Integrate with workspaces-js 2.0 example

### PR DESCRIPTION
**Pull request by ailisp**
Example written and passed for status-message. Can be use as a reference test setup for other examples and user projects

### CODE REVIEW

**Review by volovyk-s — APPROVED** [review]
Looks cool! We will need to add some helpers to Workspaces JS or to the SDK with time. But it's good for now.

**Comment by ailisp** [comment]
> Looks cool! We will need to add some helpers to Workspaces JS or to the SDK with time. But it's good for now.

Yes. Do you think `encodeCall` should better be placed in workspaces-js? I don't find a proper place for it in near-sdk-js, since `sdk` package is meant to imported in contract (quickjs).

**Comment by ailisp** [comment]
I've tested the tests still work after #12

**Comment by volovyk-s** [comment]
> > Looks cool! We will need to add some helpers to Workspaces JS or to the SDK with time. But it's good for now.
> 
> Yes. Do you think `encodeCall` should better be placed in workspaces-js? I don't find a proper place for it in near-sdk-js, since `sdk` package is meant to imported in contract (quickjs).

Maybe we will create a separate package, not sure. Let's design that after releasing SDK JS on NPM.

**Pull request merged**
