### PR TITLE
fix: Fix logging

### PR DESCRIPTION
**Pull request by petarvujovic98**
Use local instances of `signale` to scope them to commands and make them
interactive

Depends on #309

### CODE REVIEW

**Comment by ailisp** [comment]
@petarvujovic98 Thanks! This loggin improvement is great. Do you want to merge your branch into @idea404 's , or we just merge your change and close #309 ?

**Comment by petarvujovic98** [comment]
@ailisp It's all the same to me. I don't have push access so I wasn't able to push to @idea404 's #309 PR otherwise I would have just done so. We can also wait for his PR to be merged and then I will rebase and push to this PR again.

**Comment by volovyks** [comment]
@petarvujovic98 #309 was merged, please, update your PR and we will merge it as well. Thanks!

**Comment by volovyks** [comment]
Thanks for pointing out this issue @petarvujovic98 ! :)

**Pull request closed without merging**
