### PR TITLE
All examples merged to one project

### PR DESCRIPTION
**Pull request by volovyk-s**

### CODE REVIEW

**Review by ailisp — APPROVED** [review]
Nice!

**Comment by volovyk-s** [comment]
Waiting for DevRel to merge all the READMES into one. And improve that 1 README in general.

**Comment by thisisjoshford** [comment]
which README's are you referring to @volovyk-s ?

**Comment by volovyk-s** [comment]
@thisisjoshford Each separate examples project had a README file. Now all these READMEs are in this project. I think we need to merge them into one well-structured README file and make it shorter and more universal.

**Comment by thisisjoshford** [comment]
ahhh I see. Wasn't sure which READMEs you were referring to. So consolidate all README files from each example as well as the main README for this SDK, correct?

**Comment by volovyk-s** [comment]
@thisisjoshford I think the SDK should have its own README. I'm talking about the consolidation of all examples READMEs into one.

**Comment by thisisjoshford** [comment]
> @thisisjoshford I think the SDK should have its own README. I'm talking about the consolidation of all examples READMEs into one.

Yes! I agree. Was just clarifying that there are two READMEs that need enhancement from DevRel (the main SDK README as well as the consolidated examples README) Would you or someone on the tooling team be able to take the first stab at the example consolidation one?

**Comment by volovyk-s** [comment]
I have added a simple consolidated README. Margin this now.

**Pull request merged**
