### PR TITLE
issue-358: add test for migration with new fileds example

### PR DESCRIPTION
**Pull request by fospring**
## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/near/near-sdk-js/blob/master/CONTRIBUTING.md).
- [x] Commit messages follow the [conventional commits](https://www.conventionalcommits.org/) spec
- [x] **If this is a code change**: I have written unit tests.
- [x] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

Add example for migrate old contract structure to current structure with new added fileds 

## Test Plan
```
cd examples/src
pnpm run build:status-message
pnpm run build:status-message-migrate-add-field
pnpm run test:status-message-migrate-add-field
```
Test result:
```
Contract logs from dev-11117.test.near.set_status({"message":"hello"}) call: [ 'ali.test.near set_status with message hello' ]
Contract logs from dev-11117.test.near.get_status({"account_id":"ali.test.near"}) view call: [ 'get_status for account_id ali.test.near' ]
Contract logs from dev-11117.test.near.migrateState({}) call: [ 'records.length [object Object]' ]
Contract logs from dev-11117.test.near.get_status({"account_id":"ali.test.near"}) view call: [ 'get_status for account_id ali.test.near' ]
Contract logs from dev-11117.test.near.set_new_status({"message":"hello"}) call: [ 'ali.test.near set_new_status with message hello' ]
Contract logs from dev-11117.test.near.get_new_status({"account_id":"ali.test.near"}) view call: [ 'get_new_status for account_id ali.test.near' ]
  ✔ migration works (9.5s)
  ─

  1 test passed
```

## Related issues/PRs
https://github.com/near/near-sdk-js/issues/358

### CODE REVIEW

**Comment by fospring** [comment]
The test failed with error message:
```
turbo run test
```

```
examples:test:   fungible-token-lockable.ava › afterEach.always hook for Transfer failures
examples:test: 
examples:test:   Rejected promise returned by test. Reason:
examples:test: 
examples:test:   TypeError {
examples:test:     message: 'Cannot read properties of undefined (reading \'tearDown\')',
examples:test:   }
examples:test: 
examples:test:   › file://__tests__/test-fungible-token-lockable.ava.js:32:26
```
quite strange

**Comment by ailisp** [comment]
@fospring This PR looks great. The failure seems a flaky test in workspaces-js. It also happens sometimes locally. Can you create an issue and look into it?

**Comment by fospring** [comment]
> @fospring This PR looks great. The failure seems a flaky test in workspaces-js. It also happens sometimes locally. Can you create an issue and look into it?

ok

**Review by ailisp — APPROVED** [review]

**Comment by fospring** [comment]
> @fospring This PR looks great. The failure seems a flaky test in workspaces-js. It also happens sometimes locally. Can you create an issue and look into it?

https://github.com/near/workspaces-js/issues/215

**Pull request merged**
